# Generated by Django 6.0.2 on 2026-03-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercreation_is_seller_alter_usercreation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
